F Test Formula helps us to compare the variances of two different sets of values. To use F distribution under the null hypothesis, it is important to determine the mean of the two given observations at first and then calculate the variance. 

σ2=∑(x−x¯)2/n−1

In the above formula, 

σ2 is the variance

x is the values given in a set of data

x is the mean of the given Data set 

n is the total number of values in the Data set


Null Hypothesis :
    While running an F Test, it is very important to note that the population variances are equal. In more simple words, it is always assumed that the variances are equal to unity or 1. Therefore, the variances are always equal in the case of the null hypothesis

## Q1. Write a Python function that takes in two arrays of data and calculates the F-value for a variance ratio test. The function should return the F-value and the corresponding p-value for the test.

In [24]:
x = [10, 12, 22, 25, 27, 28, 41, 45, 51]
y = [14, 15, 15, 17, 18, 22, 25, 25, 27]

In [16]:
import numpy as np
import scipy

#define F-test function
def f_test(x, y):
    x = np.array(x)
    y = np.array(y)
    f = np.var(x)/np.var(y) #calculate F test statistic 
    dfn = x.size-1 #define degrees of freedom numerator 
    dfd = y.size-1 #define degrees of freedom denominator 
    p = 1-scipy.stats.f.cdf(f, dfn, dfd) #find p-value of F test statistic 
    return f, p

#perform F-test
f_test(x, y)

(4.38712, 0.019127)

(4.38712, 0.019127)

## Q2. Given a significance level of 0.05 and the degrees of freedom for the numerator and denominator of an F-distribution, write a Python function that returns the critical F-value for a two-tailed test.

In [ ]:
#find F critical value
import scipy.stats
scipy.stats.f.ppf(q=1-.05, dfn, dfd)

scipy.stats.f.ppf(q=1-.05, dfn=6, dfd=8)

## Q3. Write a Python program that generates random samples from two normal distributions with known variances and uses an F-test to determine if the variances are equal. The program should output the F- value, degrees of freedom, and p-value for the test.

In [10]:
import numpy as np
x=np.random.normal(3,size=(2, 4)) 

In [11]:
import numpy as np
y= np.random.normal(3,size=(2, 4))

In [12]:
print(x)

[[2.8009192  3.4248072  4.54712199 4.45795939]
 [3.48953489 3.74041692 2.23555215 3.78852194]]


In [13]:
print(y)

[[3.96583639 3.35561006 2.34882883 2.04219728]
 [2.75824911 2.02849591 3.36558355 2.82997397]]


In [18]:
import numpy as np


#define F-test function
def f_test(x, y):
    x = np.array(x)
    y = np.array(y)
    f = np.var(x)/np.var(y) #calculate F test statistic 
    dfn = x.size-1 #define degrees of freedom numerator 
    dfd = y.size-1 #define degrees of freedom denominator 
    p = 1-scipy.stats.f.cdf(f, dfn, dfd) #find p-value of F test statistic 
    return f, p,dfn

#perform F-test
f_test(x, y)


(1.2584689300211116, 0.38469282570454255, 7)

## Q4.The variances of two populations are known to be 10 and 15. A sample of 12 observations is taken from each population. Conduct an F-test at the 5% significance level to determine if the variances are significantly different.

In [ ]:
var1=10
var2=15
n=12
alpha=0.05



In [ ]:
F Value = Larger Sample Variance / Smaller Sample Variance = σ12  / σ22

#Step 1 : State the hypothesis

Null Hypothesis :null hypothesis assumes that the variances are equal. H0: σ1**2 = σ2**2. 

Alternate hypothesis :The variances are unequal. H1: σ12 ≠ σ22. Here, σ12 and σ22 are the symbols for variances.

In [34]:
#Step 2 : Calculate the test statistic.

#(F distribution). i.e., = σ12 / σ22 Where σ12 is assumed to be larger sample variance, and σ22 is the smaller sample variance

F_dist = 15/10
print(F_dist)

1.5


In [ ]:
#Step 3: Calculate the degrees of freedom.
Degree of freedom (df1) = n1 – 1 and Degree of freedom (df2) = n2 – 1 where n1 and n2 are the sample sizes.
n=12
n-1=11
Distribution for the test:F11,11 where n1 – 1 = 11 and n2 – 1 = 11
#Go to f table and check significance level 0.05 and df1=11 and df2=11 and check f critical value
Fdistribution is between the range  =(2.79<F value <2.85 )

In [36]:
from scipy.stats import f 
f_critical_values= scipy.stats.f.ppf(q=1-.05, dfn=11, dfd=11)
print(f_critical_values)

2.8179304699530863


In [35]:
#Result:
if F_dist > f_critical_values:
    print ("Reject the null hypothesis.")
else:
    print("Failed to reject the null hypothesis.")

Failed to reject the null hypothesis.


In [ ]:
Inference :The variances are equal. H0: σ12 = σ22. 

## Q5. A manufacturer claims that the variance of the diameter of a certain product is 0.005. A sample of 25 products is taken, and the sample variance is found to be 0.006. Conduct an F-test at the 1% significance level to determine if the claim is justified.

In [ ]:
n=25
n-1=24
var1=0.005
var2=0.006
alpha=0.01

In [ ]:
Null Hypothesis = H0 :variances are equal
    
Alternative Hypothesis = H1 =variances are not equal or greater.

In [43]:
#F statistic = F Value = σ1**2  / σ2**2 
f_stat= 0.006/0.005
print(f_stat)

1.2


In [40]:
from scipy.stats import f 
f_critical_values= scipy.stats.f.ppf(q=1-0.01,dfn=24, dfd=24)
print(f_critical_values)

2.659072104348157


In [41]:
#Result:
if F_dist > f_critical_values:
    print ("Reject the null hypothesis.")
else:
    print("Failed to reject the null hypothesis.")

Failed to reject the null hypothesis.


In [ ]:
Inference : At the 1% significance level i.e. 99% of CI we are failed to reject null hypothesis .i.e we can say varience are equal

## Q6. Write a Python function that takes in the degrees of freedom for the numerator and denominator of an F-distribution and calculates the mean and variance of the distribution. The function should return the mean and variance as a tuple.

In [ ]:
def fun_f_dist(df_denominator,df_numerator):
    mean = df_denominator / (df_denominator - 2)
    variance = (2 * (df_denominator ** 2) * (df_numerator + df_denominator - 2)) / 
               ((df_numerator * (df_denominator - 2) ** 2 * (df_denominator - 4)))
    return (mean, variance)

## Q7. A random sample of 10 measurements is taken from a normal population with unknown variance. The sample variance is found to be 25. Another random sample of 15 measurements is taken from another normal population with unknown variance, and the sample variance is found to be 20. Conduct an F-test at the 10% significance level to determine if the variances are significantly different.

In [ ]:
H0=Variances are equal
H1=Variances are different

In [47]:
Sample_count1_n1=10
Sample_count_n2=15
df1=9
df2=14
var1=25
var2=20
alpha=0.1

F_stat = var1/var2
print(F_stat)


1.25


In [ ]:
Now from the F table the critical value F(0.1, 9, 14) = 2.12

In [49]:
from scipy.stats import f 
f_critical_values= scipy.stats.f.ppf(q=1-0.1,dfn=9, dfd=14)
print(f_critical_values)

2.121954566976902


In [48]:
#Result:
if F_stat > 2.12:
    print ("Reject the null hypothesis.")
else:
    print("Failed to reject the null hypothesis.")

Failed to reject the null hypothesis.


In [ ]:
Interpretation :10% significance level ,we can say that variences are same

## Q8. The following data represent the waiting times in minutes at two different restaurants on a Saturday night: Restaurant A: 24, 25, 28, 23, 22, 20, 27; Restaurant B: 31, 33, 35, 30, 32, 36. Conduct an F-test at the 5% significance level to determine if the variances are significantly different.

In [ ]:
Restaurant A    Restaurant B
24                   31
25                   33
28                   35
23                   30
22                   32
20                   36
27                   

In [ ]:
H0 : Varience are equal
H1 : Varience are significantly different

In [88]:
import numpy as np
import scipy.stats 
res_a = [24,25,28,23,22,20,27]
res_b = [31,33,35,30,32,36]
a = np.array(res_a)
b = np.array(res_b)
alpha=0.05
# calculate variance of each group
#print(np.var(a), np.var(b))

def f_test(a, b):
    #Calculate F value
    f = np.var(a,ddof=1)/np.var(b,ddof=1)
    #print(f)
    nun = a.size-1
    #print(nun)
    dun = b.size-1
    # calculate F value from F table
    f_critical_value = scipy.stats.f.ppf(q=1-.05, dfn=nun, dfd=dun)
    # calculate P value 
    p_value = 1-scipy.stats.f.cdf(f, nun, dun)
    #print("P Value",p_value)
    print("*******By Critical Values Calculation*******\n")
    
    if f < f_critical_values:
        print ("Failed to reject Null hypothesis.\n")
    else:
        print("Reject the null hypothesis.\n")
        
    print("*********By P Values Calculation*********\n")
    if p_value >alpha:
        print ("Failed to reject Null Hypothesis.\n")
    else:
        print("Reject the null hypothesis.\n")
    return f, p_value

f_test(a, b)

*******By Critical Values Calculation*******

Failed to reject Null hypothesis.

*********By P Values Calculation*********

Failed to reject Null Hypothesis.



(1.4551907719609583, 0.3487407873968742)

In [ ]:
Inference :with 5% significance level varience are not significantly different

## Q9. The following data represent the test scores of two groups of students: Group A: 80, 85, 90, 92, 87, 83;Group B: 75, 78, 82, 79, 81, 84. Conduct an F-test at the 1% significance level to determine if the variances are significantly different.

In [89]:
group_A = [80,85,90,92,87,83]
group_B = [75,78,82,79,81,84]

In [96]:
import numpy as np

a = np.array(group_A)
b = np.array(group_B)
alpha = 0.01
n1=n2=6

def f_test(a, b):
    #Calculate F value
    f = np.var(a,ddof=1)/np.var(b,ddof=1)
    #print(f)
    nun = a.size-1
    #print(nun)
    dun = b.size-1
    # calculate F value from F table
    f_critical_value = scipy.stats.f.ppf(q=1-.01, dfn=nun, dfd=dun)
    # calculate P value 
    p_value = 1-scipy.stats.f.cdf(f, nun, dun)
    #print("P Value",p_value)
    print("*******By Critical Values Calculation*******\n")
    
    if f < f_critical_values:
        print ("Failed to reject Null hypothesis.\n")
    else:
        print("Reject the null hypothesis.\n")
        
    print("*********By P Values Calculation*********\n")
    if p_value >alpha:
        print ("Failed to reject Null Hypothesis.\n")
    else:
        print("Reject the null hypothesis.\n")
    return f, p_value

f_test(a, b)

*******By Critical Values Calculation*******

Failed to reject Null hypothesis.

*********By P Values Calculation*********

Failed to reject Null Hypothesis.



(1.9442622950819677, 0.2415521774535344)

In [ ]:
Inference :with 1% significance level varience are not significantly different