In [6]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)


In [ ]:
Consider the above code to answer further questions:

## Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

In [7]:
type(list_)

list

In [8]:
type(array_list)

numpy.ndarray

#### Yes there is difference between the type of variable list_ and array_list. as list is having datatype list but array_list datatype is numpy.ndarray.

## Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.

In [12]:
list_ = [ '1' , '2' , '3' , '4' , '5' ]
print(type(list_))
for i in list_:
    print(type(i))

<class 'list'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [13]:
array_list = np.array(object = list_)
print(type(array_list))
for i in array_list:
    print(type(i))

<class 'numpy.ndarray'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


## Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)

## Will there be any difference in the data type of the elements present in both the variables, list_ and arra_list? If so then print the data types of each and every element present in both the variables, list_ and arra_list.

#### ANS  : Yes ,there will be difference in the data type of element present in both the variables list_ and array_list

In [19]:
array_list = np.array(object = list_, dtype = int)

In [20]:
type(array_list)

numpy.ndarray

In [21]:
list_ = [ '1' , '2' , '3' , '4' , '5' ]
print(type(list_))
for i in list_:
    print(type(i))

<class 'list'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [22]:
print(type(array_list))
for i in array_list:
    print(type(i))

<class 'numpy.ndarray'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


## Consider the below code to answer further questions:


In [ ]:

import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

## Q4. Write a code to find the following characteristics of variable, num_array:
    (i) shape
    (ii) size

In [ ]:
ANS:

In [23]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [26]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

#### shape define the rows and columns in the array...first number is row value and second one is column
#### this array havng 2 rows and 3 column

In [24]:
num_array.shape

(2, 3)

#### size =Total number of element in the array
#### rows * columns

In [25]:
num_array.size

6

## Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [28]:
array1 = np.zeros((3,3))

In [29]:
array1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## Q6. Create an identity matrix of shape (5,5) using numpy functions?

[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [30]:
array2 = np.eye(5,5)

In [31]:
array2

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])